Feat: cocktail card
annkainova/cocktails pull request #4
Opened 2024-12-12 12:18 UTC by annkainova

Реализовала карточку с рецептом
Добавила перевод из унций в мл

2024-12-15 13:47 UTC, D4n1el13and37 requested changes

2024-12-15 13:47 UTC, D4n1el13and37 commented on src/shared/ui/Card/Card.tsx
> +import c from './Card.module.scss';
Лучше объявление стилей класса обновить, например как у нас уже описано cl что бы единый стиль был)

2024-12-15 13:47 UTC, D4n1el13and37 commented on src/shared/ui/Card/CardTag/CardTag.module.scss
А у нас разве нет компонента тэга?
Или он по каким то причинам не подходит ☹️

2024-12-15 13:47 UTC, D4n1el13and37 commented on src/shared/ui/Card/Ingredient/Ingredient.module.scss
> +.name {}
?)))

2024-12-15 13:47 UTC, D4n1el13and37 commented on src/shared/ui/Card/Ingredient/Ingredient.tsx
> +import c from './Ingredient.module.scss';
Опять же нейминг стилей, лучше придерживаться одного

2024-12-15 13:47 UTC, D4n1el13and37 commented on src/App.tsx
> +      strMeasure4={null}
Как будто слишком много пропсов, которые у нас даже компонент не принимает, по крайней мере согласно типизации 🤨🧐

2024-12-15 13:47 UTC, D4n1el13and37 commented on src/shared/ui/Card/Card.tsx
> +            .map((ing, index) => {
лучше не сокращать сильно, потребовалось больше времени чем хотелось бы на понимаение того что такое ing ниже в коде 🙁

2024-12-15 13:47 UTC, D4n1el13and37 commented on src/shared/ui/Card/Card.tsx
> +                  ' ml';
Круть, перевод в ml это кайф)

Может попробуем вынести это в логику хэлпера,  например oz, to ml?)

2024-12-15 13:47 UTC, D4n1el13and37 commented on src/shared/ui/Card/types.ts
У нас действительно вся эта информация должна быть в карточке? Или это просто всё с API?    
И наверное, как мне кажется мы могли бы из `strIngredient1` и `strMeasure1` сделать массивами ингридиентов(и тд.) а не каждый отдельный ингридиент пропсом   🙂

2024-12-15 14:13 UTC, D4n1el13and37 commented on src/shared/ui/Card/Card.tsx
> +          alt={`${strDrink} image`}
Имба, круто

2024-12-15 14:58 UTC, annkainova commented on src/shared/ui/Card/types.ts
Да это все с API в таком виде приходит

> strIngredient1 и strMeasure1 сделать массивами ингридиентов(и тд.) а не каждый отдельный ингридиент пропсом 🙂

Я хотела сделать вот так массивами. Но я увидела что d API вот такой штукой отдает и решила так оставить)
https://www.thecocktaildb.com/api/json/v1/1/search.php?s=margarita 

Думаешь можно как то переделать в лучший вид?

2025-04-21 10:35 UTC, annkainova commented on src/shared/ui/Card/Card.tsx
> +import c from './Card.module.scss';
Хорошо, это легко ))

2025-04-21 11:23 UTC, annkainova commented on src/shared/ui/Card/CardTag/CardTag.module.scss
Готово, заменила на существующий компонет)

2025-04-21 12:21 UTC, annkainova commented
Хэхэй, что наделала:

1. Добавила нормализоатор данных из API. Они приходят гинатский, у нас преобразуется в массив ingredients
2. Вынесла перевод oz → ml в отдельный helper
3. Поменяла мой тег на твой. В самом теге добавила скрыватель крестика. Потому что в карточке крестик не нужен)
Нужно подумать насчет дизайна этого тега. Что бы он был одинаковый везде)

2025-04-21 16:19 UTC, D4n1el13and37 commented on src/App.tsx
> +console.log(cocktail);
Лог попався)

2025-04-21 16:19 UTC, D4n1el13and37 commented on src/shared/ui/Card/Card.tsx
> +          <SelectTag content={alcoholic} hideDeleteIcon />
Может можно как то через цикл?)
А то как будто повторения

2025-04-21 16:19 UTC, D4n1el13and37 commented on src/types/CardInterface.ts
> +// Это тип того что приходит с API. Возможно не тут должно лежать)
Вроде норм)
Можно создать два файлика, один с респозом другой с реквестом)

2025-04-21 16:19 UTC, D4n1el13and37 commented on src/utils/convertToMl.ts
> +  if (!value) return undefined;
Нам действительно нужно возвращать undefined?

2025-04-21 16:19 UTC, D4n1el13and37 commented on src/utils/normalizeCocktail.ts
Круть 😎

2025-04-21 16:19 UTC, D4n1el13and37 commented on src/utils/normalizeCocktail.ts
> +    return name ? [{ name, amount: amount || undefined }] : [];
А это должно именно массивом быть?

2025-04-21 16:19 UTC, D4n1el13and37 commented on src/utils/normalizeCocktail.ts
> +  const ingredients = Array.from({ length: 15 }).flatMap((_, i) => {
Это у нас массив массивов?

2025-04-23 07:42 UTC, D4n1el13and37 approved these changes

2025-04-23 07:42 UTC, merged